a=float(input("enter first number:"))
b=float(input("enter second number:"))
print("sum:",a+b)
print("subtraction:",a-b)
print("multiplication:",a*b)
print("division:",a/b)
print("floor division:",a//b)
print("remainder:",a%b)
print("exponential:",a**b)